name: Deploy
on:
  workflow_dispatch:
    inputs:
      name:
        description: "DockerHub"
  # push:
  #   branches: main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        run: |
          env
          make build-push