name: Deploy
on:
  workflow_dispatch:
    inputs:
      name:
        description: "DockerHub"

env:
  USERNAME: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_USERNAME }}        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: echo $DOCKER_TOKEN | docker login -u $USERNAME --password-stdin 
      - name: Push
        run: make build-push