name: Deploy
on:
 workflow_dispatch:
    inputs:
      androidsdkversion:
        default: "8092744"
        description: "Android SDK Version"
      androidversion:
        default: "27"
        description: "Android Version"
      androidtoolsversion:
        default: "27.0.3"
        description: "Android Tools Version"

jobs:
  deployment:
    name: Android sdk ${{ github.event.inputs.androidsdkversion }} v${{ github.event.inputs.androidversion }} tools ${{ github.event.inputs.androidtoolsversion }}
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: |
          env
          make build-push \
            ANDROID_SDK_VERSION=${{ github.event.inputs.androidsdkversion }} \
            ANDROID_VERSION=${{ github.event.inputs.androidversion }} \
            ANDROID_BUILD_TOOLS_VERSION=${{ github.event.inputs.androidtoolsversion }}
